Updated LookForIP to have muliple functions

diff --git a/scripts/LookForIP b/scripts/LookForIP
--- a/scripts/LookForIP
+++ b/scripts/LookForIP
@@ -1,6 +1,6 @@
 #!/etc/bash
 
-#global shit like array and variables
+#text configs. To make nice colorfull and bold text.
 count=0
 red="\e[31m"
 green="\e[32m"
@@ -8,10 +8,15 @@ purple="\e[35m"
 cyan="\e[36m"
 blank="\e[0m"
 
+bold=$(tput bold)
+normal=$(tput sgr0)
+
+#the next comment is old and wrong. But i'm too lazy to remove it.
 #this one look scary, but it's just cutting the result of running "ifcinfig eno1" to only display the ip
 #network=$(ifconfig eno1 | grep "inet " | cut -d " " -f 10) # <--- This only woks with "net-tools" and olnly if you're using eno1. not practical
 network=$(ip route get 1.1.1.1 | grep -oP "src \K\S+") # This is supposed to see what you use, Like: eth0, wlan0, enp3s0,
 
+# This is the ASCII banners
 bigtext=('
   mmmmmm   mmmmmm                                                                         
   ""##""   ##""""#m                                                                       
@@ -112,11 +117,12 @@ ___) (___| )      /\____) || (____/\| )   ( || )  \  || )  \  || (____/\| ) \ \_
 
 )
 
-#cool welcome message in a nice cyan color
+# Startp screen with color and animations. just looks nice
 startup() {
   clear
   echo ""
   echo -e "${cyan}${bigtext[($RANDOM % 7)]}${blank}"
+  echo -e "${cyan}By: @JustCallMeDullp${blank}"
 
   for x in {1..4}; do
     sleep 0.5
@@ -131,62 +137,137 @@ startup() {
   sleep 2
 }
 
-#this gives the user sometihng to look at while the script runs its magic.
-search() {
+# Like startup, it gives the user sometihng to look at while the script runs its magic.
+welcome() {
   echo ""
   echo -e "${cyan}----------<<Welcome to IPscanner>>----------${blank}"
   echo -e "${green}Your address is:${blank}"
   echo -e "${red}$network${blank}"
   echo ""
   sleep 1.5
-  echo -e "Now searching for addresses on the network: ${purple}${network%.*}.x${blank}" #"\e[35${network%.*}\e[0m")
-  sleep 2.5
 }
 
-#This is where the magic actually happens.
+#This is the Scan etire network thingymajig
 scan() {
-  for ip in {1..254}; do          #this is to go trough every address from 1 to 254 and put it in a variable named "ip"
-    address="${network%.*}.${ip}" # this is to add the "ip" variable to the "network" varable so we get something like 192.168.20.IP
+  # Local variables are yanked from "what"
+  local from=$1
+  local to=$2
+  echo -e "Now searching for addresses on the network: ${purple}${network%.*}.x${blank}" #"\e[35${network%.*}\e[0m")
+  sleep 2.5
+  for ip in $( # We use the 'from' and 'to' from 'wait' to go trough the addresses the user wants
+    seq "$from" "$to"
+  ); do
+    address="${network%.*}.${ip}" # this is to add the "ip" ('from' and 'to') variable to the "network" varable so we get something like 192.168.20.IP
 
-    ping -c 1 -W 0.3 "${address}" >/dev/null 2>&1 #This is the thingy that pings an address and looks for a response
+    ping -c 1 -W 0.3 "${address}" >/dev/null 2>&1 #This is the thingy that pings an address and waits for a response
 
-    if [ $? -eq 0 ]; then # this looks for adresses that did not respond
-
+    if [ $? -eq 0 ]; then # this looks for adresses that did respond and prints the address with a nice green [up]
       if [ ${ip} -lt 10 ]; then
-        echo -e "${address} ${green}  [up]${blank}--------- ${ip}/254"
-
-      elif [ ${ip} -lt 255 ] && [ ${ip} -gt 9 ]; then
-        echo -e "${address} ${green} [up]${blank}-------- ${ip}/254"
-
-      elif [ ${ip} -lt 255 ] && [ ${ip} -gt 99]; then
-        echo -e "${address} ${green} [up]${blank}----- ${ip}/254"
-
+        echo -e "${address}${green}     [up]${blank}--------- ${ip}/254"
+      elif [ ${ip} -lt 100 ] && [ ${ip} -gt 9 ]; then
+        echo -e "${address}${green}    [up]${blank}-------- ${ip}/254"
+      elif [ ${ip} -lt 255 ] && [ ${ip} -gt 99 ]; then
+        echo -e "${address}${green}   [up]${blank}------- ${ip}/254"
       fi
 
-    elif [ $? -ne 0 ]; then
-
+    elif [ $? -ne 0 ]; then # this looks for the addresses that did NOT respond, and prints the address with a nice red [down]
       if [ ${ip} -lt 10 ]; then
-        echo -e "${address} ${red} [down]${blank}-------- ${ip}/254"
-
-      elif [ ${ip} -lt 255 ] && [ ${ip} -gt 9 ]; then
-        echo -e "${address} ${red}[down]${blank}------- ${ip}/254"
-
-      elif [ ${ip} -lt 255 ] && [ ${ip} -gt 99]; then
-        echo -e "${address} ${red}[down]${blank}---- ${ip}/254"
-
+        echo -e "${address}${red}    [down]${blank}-------- ${ip}/254"
+      elif [ ${ip} -lt 100 ] && [ ${ip} -gt 9 ]; then
+        echo -e "${address}${red}   [down]${blank}------- ${ip}/254"
+      elif [ ${ip} -lt 255 ] && [ ${ip} -gt 99 ]; then
+        echo -e "${address}${red}  [down]${blank}------ ${ip}/254"
       fi
     fi
-
     ((count += 1)) #this is just to show how many times the code ran. other words, how many adresses was pinged.
+  done
+  echo -e "\e[33mscanned: $count addresses\e[0m" # print in yellow how many addresses was pinged
+}
+
+# ----------------------------------------------------------------------------------------------------------------------------------
+# And this is ofc, the first option.
+first() {
+  for ip in {1..254}; do
+    address="${network%.*}.${ip}"                 # this is to add the 'ip' variable to the "network" varable so we get something like 192.168.20.IP
+    ping -c 1 -W 0.1 "${address}" >/dev/null 2>&1 #This is the thingy that pings an address and waits for a response
+
+    if [ $? -eq 0 ]; then # this looks for adresses that did respond and prints the address with a nice green [up]
+      if [ ${ip} -lt 10 ]; then
+        echo -e "${address}${green}     [up]${blank}--------- ${ip}/254"
+      elif [ ${ip} -lt 100 ] && [ ${ip} -gt 9 ]; then
+        echo -e "${address}${green}    [up]${blank}-------- ${ip}/254"
+      elif [ ${ip} -lt 255 ] && [ ${ip} -gt 99 ]; then
+        echo -e "${address}${green}   [up]${blank}------- ${ip}/254"
+      fi
+    fi
   done
 }
 
-# This is where we call the functions and in order
-startup
-search
-wait
-scan
-wait
+# ----------------------------------------------------------------------------------------------------------------------------------
+# Then this must me... The second option
+second() {
+  for ip in {1..254}; do
+    address="${network%.*}.${ip}"                 # this is to add the 'ip' variable to the "network" varable so we get something like 192.168.20.IP
+    ping -c 1 -W 0.1 "${address}" >/dev/null 2>&1 #This is the thingy that pings an address and waits for a response
 
-#and, can't forget the line that tells the user how many addresses was checked
-echo -e "\e[33mscanned: $count addresses\e[0m"
+    if [ $? -ne 0 ]; then # this looks for adresses that did NOT respond and prints the address with a red [down]
+      if [ ${ip} -lt 10 ]; then
+        echo -e "${address}${red}    [down]${blank}-------- ${ip}/254"
+      elif [ ${ip} -lt 100 ] && [ ${ip} -gt 9 ]; then
+        echo -e "${address}${red}   [down]${blank}------- ${ip}/254"
+      elif [ ${ip} -lt 255 ] && [ ${ip} -gt 99 ]; then
+        echo -e "${address}${red}  [down]${blank}------ ${ip}/254"
+      fi
+    fi
+  done
+}
+
+# ----------------------------------------------------------------------------------------------------------------------------------
+# Take a wild fucking guess.
+third() {
+  echo "cool, now. How many addresses do you want to see?"
+  sleep 0.5
+  echo -e "${network%.*}.${red}1-254$blank}"
+  read -p "from ${network%.*}.1-254 : " from # we use '-p' again to read the input and asign a variable on the same line.
+  read -p "to ${network%.*}.1-254: " to
+  if [ $from -gt $to ]; then
+    echo "Hey, no. You Can't do that. 'From' needs to be grater than 'to'"
+  else
+    echo "$from..$to"  # this just prints the options you chose
+    scan "$from" "$to" # this starts the scan function and sends the 'from' and 'to' variable to run the scan the correct ammount of time
+  fi
+}
+
+# ----------------------------------------------------------------------------------------------------------------------------------
+
+# This is the options menu. Also known as "what" as in What am i gonna do rn.
+what() {
+  echo "What do you wish to do?"
+  echo "
+  1. Show all active IPs
+  2. Show all inactive IPs
+  3. Full scan
+  "
+  read -p ">> " choice                 # This uses "-p" for ptomt. so that the string and the input is on the same line
+  if ! [[ ${choice} =~ ^[1-3] ]]; then # check if the choice is NOT a number between 1 and 3
+    clear
+    echo -e "${bold}Not an option. Select [1-3]${normal}"
+    what
+  fi
+
+  # Here we call the magic we gave the options
+  if [ ${choice} -eq 1 ]; then
+    first
+  elif [ ${choice} -eq 2 ]; then
+    second
+  elif [ ${choice} -eq 3 ]; then
+    third
+  fi
+}
+
+# This is where we start the program, and the order we do so in.
+startup
+welcome
+wait
+what
+wait
